databases:
  - name: biobook-db
    databaseName: biobook_db
    user: biobook_user
    plan: free

services:
  - type: web
    name: biobook-bot
    env: docker
    plan: free
    region: frankfurt
    preDeployCommand: "php artisan config:clear && php artisan migrate --force"
    envVars:
      - key: APP_DEBUG
        value: "true"
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - fromDatabase:
          name: biobook-db
          property: host
        key: DB_HOST
      - fromDatabase:
          name: biobook-db
          property: database
        key: DB_DATABASE
      - fromDatabase:
          name: biobook-db
          property: user
        key: DB_USERNAME
      - fromDatabase:
          name: biobook-db
          property: password
        key: DB_PASSWORD
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://biobook-bot.onrender.com
