services:
  - type: web
    name: biobook-bot
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
